# Generated by Django 2.2 on 2019-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_metering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumedenergy',
            name='energy_amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consumedenergy',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20),
        ),
    ]
