# Generated by Django 2.2 on 2019-10-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_metering', '0002_auto_20190918_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyinvoice',
            name='payment_confirmation',
        ),
        migrations.AlterField(
            model_name='energytransaction',
            name='producer_community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_energy', to='comunitaria.Community'),
        ),
    ]
