# Generated by Django 2.2 on 2019-12-30 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comunitaria', '0050_communityticket_confirmations_users'),
        ('energy_metering', '0003_auto_20191001_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('serial_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(choices=[('operative', 'operative'), ('inoperative', 'inoperative')], default='operative', max_length=100)),
                ('error_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=350, null=True)),
                ('communities', models.ManyToManyField(related_name='authorized_chargepoints', to='comunitaria.Community')),
            ],
        ),
        migrations.CreateModel(
            name='EVTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunitaria.UserCommunity')),
            ],
        ),
        migrations.CreateModel(
            name='CPMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('central_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_metering.CentralSystem')),
                ('charge_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy_metering.ChargePoint')),
            ],
        ),
    ]
