# Generated by Django 2.2 on 2020-01-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_metering', '0004_centralsystem_chargepoint_cpmessage_evtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='evtransaction',
            name='charge_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy_metering.ChargePoint'),
        ),
        migrations.AddField(
            model_name='evtransaction',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy_metering.ConsumedEnergy'),
        ),
    ]
