# Generated by Django 2.2 on 2020-01-28 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_metering', '0005_auto_20200121_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepoint',
            name='status',
            field=models.CharField(default='available', max_length=100),
        ),
        migrations.CreateModel(
            name='CPConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(default='available', max_length=100)),
                ('status', models.CharField(default='available', max_length=100)),
                ('charge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_metering.ChargePoint')),
            ],
        ),
    ]
