# Generated by Django 2.2 on 2020-03-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_metering', '0006_auto_20200128_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityenergyinfo',
            name='ex_community_energy_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='communityenergyinfo',
            name='in_community_energy_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
