# Generated by Django 2.2 on 2021-08-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_metering', '0007_auto_20200310_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityenergyinfo',
            name='apitoshi_apikey',
        ),
        migrations.RemoveField(
            model_name='energyinvoice',
            name='apitoshi_payment_id',
        ),
    ]
